"""Carbon market adapter Protocol — pluggable simulated/real exchange interface."""
from typing import Protocol, runtime_checkable


@runtime_checkable
class CarbonMarketAdapter(Protocol):
    """18-method interface for carbon market operations."""

    # ── Market Data ──
    async def get_order_book(self, allowance_type: str, depth: int): ...
    async def get_latest_price(self, allowance_type: str) -> float: ...
    async def get_ohlcv(self, allowance_type: str, interval: str, start: float, end: float): ...
    async def subscribe_tick(self, allowance_type: str, callback) -> None: ...

    # ── Trading ──
    async def place_order(self, order_data: dict) -> dict: ...
    async def cancel_order(self, order_id: str) -> bool: ...
    async def get_order(self, order_id: str) -> dict: ...
    async def get_my_orders(self, plant_id: str, status: str = None) -> list: ...
    async def get_my_trades(self, plant_id: str, start: float = None, end: float = None) -> list: ...
    async def get_trade_fee(self, trade_value: float) -> float: ...

    # ── Allowance Lifecycle ──
    async def receive_allocation(self, plant_id: str, period: str, qty: float, source: str) -> dict: ...
    async def participate_auction(self, plant_id: str, bid_qty: float, bid_price: float) -> dict: ...
    async def transfer(self, from_plant: str, to_plant: str, qty: float, atype: str) -> dict: ...
    async def surrender(self, plant_id: str, period: str, qty: float, atype: str) -> dict: ...

    # ── Holdings ──
    async def get_holdings(self, plant_id: str, period: str) -> dict: ...
    async def get_holdings_snapshot(self, plant_id: str, date: str) -> dict: ...

    # ── Market Info ──
    async def get_market_calendar(self) -> dict: ...
    async def get_compliance_deadline(self, period: str): ...
